### ISSUE TITLE
Sent messages(from flutter client) are not displaying on xmtp.chat or other clients.

### ISSUE THREAD

**Issue by nileshrathore** [xmtp/xmtp-flutter#28]
I am experiencing an issue where messages sent from a Flutter client using Wallet Connect are not being displayed on xmtp.chat or other clients. However, when using a random wallet, the messages are displayed correctly. 

It is worth noting that the sent messages from the Flutter client are being displayed on other Flutter clients, but not on xmtp.chat. 

All clients are pointed to 'production.xmtp.network' and received messages are being displayed correctly on all clients.

**Comment by nplasterer** [comment]
![telegram-cloud-photo-size-5-6163405982932251554-y](https://user-images.githubusercontent.com/3522670/210156364-e9251d73-5dbe-4a1b-a830-b976965ccf8b.jpg)

**Comment by nplasterer** [comment]
I believe this issue has been fixed. Please feel free to reopen if that's not the case.
