### ISSUE TITLE
Conversations created on flutter sdk are not visible on other clients!

### ISSUE THREAD

**Issue by nileshrathore** [xmtp/xmtp-flutter#35]
I have created a few new conversations with flutter SDK and those are not visible on xmtp.chat. And when I try to message the same wallet from xmtp.chat, one more new conversation is created. So now I see two convos on the flutter client from the same wallet and one convo on xmtp.chat!

<img width="341" alt="Screenshot 2023-01-09 at 15 18 32" src="https://user-images.githubusercontent.com/20648391/211427532-4d0c9615-f1dc-4e00-ace0-ec886bacbc1f.png">

![IMG_3146](https://user-images.githubusercontent.com/20648391/211427572-ca86971f-d62c-4ff6-90a3-f78284a722d8.jpg)

**Comment by neekolas** [comment]
I was able to reproduce this issue, and can add the following context. It appears that conversations on Flutter have a mismatch between the timestamp in the `xmtp.Envelope` and the message headers. When attempting to decrypt this message in the JS SDK I get the following error message.

```
Error in listEnvelopes mapper Error: envelope and header timestamp mistmatch
```

**Comment by neekolas** [comment]
@dmccartney we'll also want to add validation for the headers and envelope timestamp matching to the Flutter SDK to mirror the behaviour in JS. That way invalid conversations will be treated consistently between environments.
