### ISSUE TITLE
Bug: Incomplete Conversation Retrieval from SDK (Limit: 102 Conversations)

### ISSUE THREAD

**Issue by nileshrathore** [xmtp/xmtp-flutter#70]
### Describe the bug

I am currently experiencing a limitation with the SDK where it only returns a maximum of 102 conversations from my wallet, despite having around 200 conversations in my wallet.

**Comment by nplasterer** [comment]
We recently fixed this bug in android https://github.com/xmtp/xmtp-android/pull/74/files it should be a simple fix from the query method to a batch envelopes method.

So in this code we should no longer be calling query
https://github.com/xmtp/xmtp-flutter/blob/main/lib/src/conversation/conversation_v2.dart#L93-L101

Instead it should look something like

```dart
var listing = await api.client.envelopes(xmtp.QueryRequest(
      contentTopics: [Topic.userInvite(_me.hex)],
      startTimeNs: start?.toNs64(),
      endTimeNs: end?.toNs64(),
      pagingInfo: xmtp.PagingInfo(
        limit: limit,
        direction: sort,
      ),
    ));
```

It's possible an envelopes method on the client doesn't exist yet and if thats the case you'll need to write something like this https://github.com/xmtp/xmtp-android/blob/main/library/src/main/java/org/xmtp/android/library/ApiClient.kt#L125-L136 to iterate through all the pages and return all the envelopes (conversations).
